apps/core/urls.py
from django.urls import path

# router = routers.DefaultRouter()
# router.register(r'rayon', RayonViewSet)
from apps.core.api import RayonViewSetLV, RayonViewSetDV, DoctorViewSetLV, \
    DoctorViewSetDV, MKB10ViewSetLV, MKB10ViewSetDV,  OtchetyViewSetLV, OtchetyViewSetDV
from apps.core.api2 import BeremennayaViewSetLV, BeremennayaViewSetDV, KonsultaciayaViewSetLV, KonsultaciayaViewSetDV, \
    AnketaViewSetLV, AnketaViewSetDV, NapravlenieViewSetLV, NapravlenieViewSetDV, NovorojdenniyViewSetLV, \
    NovorojdenniyViewSetDV, SmenaJKViewSetLV, SmenaJKViewSetDV
from apps.core.views import home, sbor_znachenii_spravocnix_tabliz, vhod, vihod, loginpage

urlpatterns = [
    path('api/sbor_znachenii_spravocnix_tabliz/', sbor_znachenii_spravocnix_tabliz),
    path('api/rayon/', RayonViewSetLV.as_view()),
    path('api/rayon/<int:pk>', RayonViewSetDV.as_view()),

    path('api/doctor/', DoctorViewSetLV.as_view()),
    path('api/doctor/<int:pk>', DoctorViewSetDV.as_view()),

    path('api/mkb10/', MKB10ViewSetLV.as_view()),
    path('api/mkb10/<int:pk>', MKB10ViewSetDV.as_view()),

    path('api/otchety/', OtchetyViewSetLV.as_view()),
    path('api/otchety/<int:pk>', OtchetyViewSetDV.as_view()),
    # path('api/', include(router.urls)),
    # path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    path('', home, name='home'),
    path('login', loginpage, name='login'),
    path('vhod', vhod, name='vhod'),
    path('vihod', vihod, name='vihod'),

    path('api2/beremennaya/', BeremennayaViewSetLV.as_view(), name='beremennaya_lv'),
    path('api2/beremennaya/<int:pk>', BeremennayaViewSetDV.as_view(), name='beremennaya_dv'),

    path('api2/anketa/<int:beremenya_id>/', AnketaViewSetLV.as_view(), name='anketa_lv'),
    path('api2/anketa/<int:beremenya_id>/<int:pk>', AnketaViewSetDV.as_view(), name='anketa_dv'),

    path('api2/napravlenie/<int:beremenya_id>/', NapravlenieViewSetLV.as_view(), name='napravlenie_lv'),
    path('api2/napravlenie/<int:beremenya_id>/<int:pk>', NapravlenieViewSetDV.as_view(), name='napravlenie_dv'),

    path('api2/konsultaciaya/<int:beremenya_id>/', KonsultaciayaViewSetLV.as_view(), name='konsultaciaya_lv'),
    path('api2/konsultaciaya/<int:beremenya_id>/<int:pk>', KonsultaciayaViewSetDV.as_view(), name='konsultaciaya_dv'),

    path('api2/novorojdenniy/<int:beremenya_id>/', NovorojdenniyViewSetLV.as_view(), name='novorojdenniy_lv'),
    path('api2/novorojdenniy/<int:beremenya_id>/<int:pk>', NovorojdenniyViewSetDV.as_view(), name='novorojdenniy_dv'),

    path('api2/smenaJK/<int:beremenya_id>/', SmenaJKViewSetLV.as_view(), name='smenaJK_lv'),
    path('api2/smenaJK/<int:beremenya_id>/<int:pk>', SmenaJKViewSetDV.as_view(), name='smenaJK_dv'),
]

centr/urls.py
from django.contrib import admin
from django.urls import path, include

from scripts.ZagruzkaPolzovatelei import script_zagruzka_polzovatelei

urlpatterns = [
    path('',  include('apps.core.urls')),
    path('script_zagruzka_polzovatelei', script_zagruzka_polzovatelei),
    path('admin/', admin.site.urls),
]

apps/core/forms.py
from django import forms

from apps.core.models import Beremennaya, Anketa, Ishod, Konsultaciaya, Napravlenie, Smena_JK_u_beremennoy, Novorojdenniy


class BeremennayaFormPart1(forms.ModelForm):
    class Meta:
        model = Beremennaya
        fields = [
            'nomer',
            'stepen_riska',
            'jk_beremennoy',
            'data_vzyatiya',
            'vrach',
            'fio',
            'data_rojdeniya',
            'vozrast',
            'mesto_postoyannogo_projivaniya',
            'nomer_telefona',
            'nomer_oms',
        ]

    data_vzyatiya = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}), label='Дата взятия')
    data_rojdeniya = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}),
                                     label='Дата рождения')


class BeremennayaVredniePrivichki(forms.ModelForm):
    def as_p(self):
        "Return this form rendered as HTML <p>s."
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(field)s %(help_text)s%(label)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )

    class Meta:
        model = Beremennaya
        fields = [
            'p110_vrednie_privichki_kurenie',
            'p120_vrednie_privichki_alco',
            'p130_vrednie_privichki_narko',
            'p140_vrednie_privichki_toxi',
        ]


class BeremennayaVrednieFactori(forms.ModelForm):
    def as_p(self):
        "Return this form rendered as HTML <p>s."
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(field)s %(help_text)s%(label)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )

    class Meta:
        model = Beremennaya
        fields = [
            'p150_vrednie_factori_truda_himicheskie',
            'p160_vrednie_factori_truda_radioactiv',
            'p180_vrednie_factori_truda_priem_lekarstvennih_sredstv',
            'p170_vrednie_factori_truda_neudvl_jil_ysloviya',
        ]


class AnketaForm(forms.ModelForm):
    class Meta:
        model = Anketa
        fields = '__all__'


    data_zapolneniya_anketi_vrachem = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}), label='Дата заполнения анкеты врачем')
    data_provedeniya_prenatalnogo_konsiliuma = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}), label='Дата проведения пренатального консилиума')


class NovorojdenniyForm(forms.ModelForm):
    class Meta:
        model = Novorojdenniy
        fields = '__all__'





class KonsultaciayaForm(forms.ModelForm):
    class Meta:
        model = Konsultaciaya
        fields = '__all__'

    otpravleno = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}), label='Дата отправления')

class NapravlenieForm(forms.ModelForm):
    class Meta:
        model = Napravlenie
        fields = ['nomer_beremennoy',
                  'cel_napravleniya',
                  'punkt_napravleniya',
                  'predpolagaemyi_diagnoz',
                  'diagnoz_podtverjden',
                  'data',
                  ]

    data = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}), label='Дата явки беременной в ЖК с результатом направления')

class IshodForm(forms.ModelForm):
    class Meta:
        model = Ishod
        fields = '__all__'

    data_ishoda = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}), label='Дата исхода')


class BeremennayaForm(forms.ModelForm):
    class Meta:
        model = Beremennaya
        fields = '__all__'

    data_pervogo_dnya_posledney_menstruacii = forms.DateField(required=False, widget=forms.DateInput(attrs={'type': 'date'}),
                                     label='Дата первого дня последней менструации')

class SmenaJKForm(forms.ModelForm):
    class Meta:
        model = Smena_JK_u_beremennoy
        fields = '__all__'


class BeremennayaInfekcionnieBolezniForm(forms.ModelForm):
    def as_p(self):
        "Return this form rendered as HTML <p>s."
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(field)s %(help_text)s%(label)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )

    class Meta:
        model = Beremennaya
        fields = [
            'qf1070_infekcionnie_bolezni_gripp',
            'qf1090_infekcionnie_bolezni_sifilis',
            'qf1110_infekcionnie_bolezni_vich',
            'qf1130_infekcionnie_bolezni_krasnuha',
            'qf1080_infekcionnie_bolezni_orvi',
            'qf1100_infekcionnie_bolezni_tuberkulez',
            'qf1120_infekcionnie_bolezni_virusniy_gepatit',
            'qf1135_infekcionnie_bolezni_toksoplazmoz',
            'qf1136_infekcionnie_bolezni_virusniy_cmvi',
        ]


class BeremennayaRazmerTazaForm(forms.ModelForm):
    def as_p(self):
        "Return this form rendered as HTML <p>s."
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(field)s %(help_text)s%(label)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )

    class Meta:
        model = Beremennaya
        fields = [
            'p250_razmer_taza_ds',
            'p260_razmer_taza_dc',
            'p270_razmer_taza_dt',
            'p280_razmer_taza_cd',
            'p290_razmer_taza_ce',
            'p300_razmer_taza_cv',
        ]


class BeremennayaZabolevanieVnutForm(forms.ModelForm):
    def as_p(self):
        "Return this form rendered as HTML <p>s."
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(field)s %(help_text)s%(label)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )

    class Meta:
        model = Beremennaya
        fields = [
            'p380_zabolevanie_vnut_pol_organov_vospalenie_roj',
            'p390_zabolevanie_vnut_pol_organov_opuhl',
            'p400_zabolevanie_vnut_pol_organov_mioma',
            'p410_zabolevanie_vnut_pol_organov_gipoplaziya',
            'p420_zabolevanie_vnut_pol_organov_poroki',
            'p430_zabolevanie_vnut_pol_organov_operacii_pred',
            'p440_zabolevanie_vnut_pol_organov_operacii_matk',
            'p450_zabolevanie_vnut_pol_organov_istmiko',
            'p455_zabolevanie_vnut_pol_organov_onkologiya',
        ]


class BeremennayaOslojneniyaBeremennostiForm(forms.ModelForm):
    def as_p(self):
        "Return this form rendered as HTML <p>s."
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(field)s %(help_text)s%(label)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )

    class Meta:
        model = Beremennaya
        fields = [
            'op660_oslojneniya_beremennosti_anemez',
            'op670_oslojneniya_beremennosti_anemez_fetoplacent',
            'op680_oslojneniya_beremennosti_anemez_obostrenie',
            'op690_oslojneniya_beremennosti_anemez_prejdevremennoy',
            'op700_oslojneniya_rodov',
        ]


class BeremennayaOslojneniyaRodovForm(forms.ModelForm):
    def as_p(self):
        "Return this form rendered as HTML <p>s."
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(field)s %(help_text)s%(label)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )

    class Meta:
        model = Beremennaya
        fields = [
            'op700_oslojneniya_rodov',
            'op710_oslojneniya_rodov_osl_razrivom',
            'op720_oslojneniya_rodov_osl_krovotech',
            'op730_oslojneniya_rodov_osl_gnoyno',
            'op740_oslojneniya_rodov_osl_mertvoroj',
            'op750_kesarevo_sechenie',
            'op751_rubec_na_matke',
            'op760_oslojneniya_anomaliyami_rodovoy_deyatelnosti',
            'op770_klinicheski_uzkiy_taz',
            'op780_plodorazrushayushaya_operaciya',
        ]


class BeremennayaNovorojdenniyPlodForm(forms.ModelForm):
    def as_p(self):
        "Return this form rendered as HTML <p>s."
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(field)s %(help_text)s%(label)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )

    class Meta:
        model = Beremennaya
        fields = [
            'op790_novorojdenniy_plod_smert',
            'op800_novorojdenniy_plod_ves',
            'op810_novorojdenniy_plod_nevrolgiych',
            'op820_novorojdenniy_plod_vpr',
            'op830_novorojdenniy_plod_perinatalnie',
        ]



class BeremennayaBolezniEndokrForm(forms.ModelForm):
    def as_p(self):
        "Return this form rendered as HTML <p>s."
        return self._html_output(
            normal_row='<p%(html_class_attr)s>%(field)s %(help_text)s%(label)s</p>',
            error_row='%s',
            row_ender='</p>',
            help_text_html=' <span class="helptext">%s</span>',
            errors_on_separate_row=True,
        )

    class Meta:
        model = Beremennaya
        fields = [
            'qf1150_saharniy_diabed',
            'qf1151_gestacionniy_saharniy_diabed',

apps/core/templates/beremennya/beremennaya_tabs/napravlenie/btn_open_window_napravlenie.html
{% if user.polzovatel.rol == 1 or user.polzovatel.rol == 2 or user.polzovatel.rol == 3 %}
    <button class="topmenu menubtn" id="btn_open_window_napravlenie">Новое направление</button>
    <button class="topmenu menubtn" id="btn_delete_konsultaciya">Удалить направление</button>
{% endif %}
<script>

    class BtnWindowNapravlenie {
        constructor($btn_open_window_napravlenie, $window, $obj_window_napravlenie) {
            this.$btn = $btn_open_window_napravlenie;
            this.$window = $window;
            this.obj_window_napravlenie = obj_window_napravlenie;
            this.on_click_toogle_btn();

        }

        on_click_toogle_btn() {
            let self = this;
            this.$btn.click(function () {
                    let tgl = self.$window.jqxWindow('isOpen');
                    let rowindexes = $('.tabliza_beremennaya').jqxGrid('getselectedrowindexes');
                    let data = $('.tabliza_beremennaya').jqxGrid('getrowdatabyid', rowindexes);
                    let sr = data.id;
                    if (tgl === false) {
                        document.getElementById("btn_open_window_napravlenie").classList.remove('menubtn');
                        document.getElementById("btn_open_window_napravlenie").classList.add('menubtn_toggle');
                        document.getElementById('novoe_napravlenie').reset();
                        obj_window_napravlenie.open2(data.id);
                        self.$window.jqxWindow('bringToFront');
                        NAPRAVLENIE_ID = 0;

                    } else {
                        document.getElementById("btn_open_window_napravlenie").classList.remove('menubtn_toggle');
                        document.getElementById("btn_open_window_napravlenie").classList.add('menubtn');
                        self.$window.jqxWindow('close');
                    }
                }
            )
            ;
        }
    }

    $btn_open_window_napravlenie = $('#btn_open_window_napravlenie')
    $(function () {
        new BtnWindowNapravlenie($btn_open_window_napravlenie, $window_napravlenie);
    })
    $(function () {
        $window_napravlenie.on('close', function (event) {
            document.getElementById("btn_open_window_napravlenie").classList.remove('menubtn_toggle');
            document.getElementById("btn_open_window_napravlenie").classList.add('menubtn');
        });
    })

</script>

apps/core/templates/beremennya/beremennaya_tabs/napravlenie/napravleniya.html
<div class="default">
    {% include 'beremennya/beremennaya_tabs/napravlenie/btn_open_window_napravlenie.html' %}
</div>
{% include 'beremennya/beremennaya_tabs/napravlenie/tabliza_napravlenie.html' %}

apps/core/templates/beremennya/beremennaya_tabs/napravlenie/tabliza_napravlenie.html
<div style="border-right-width: 0; border-left-width: 0;" class="tabliza_napravlenie"></div>


<script>
    'use strict';

    class TablizaNapravlenie {

        constructor($grid) {
            let self = this;
            this.$grid = $grid;
            this.obj_window_napravlenie = obj_window_napravlenie;
            this.$window_napravlenie = $window_napravlenie;
            this.$grid.jqxGrid(self.nastroiki_grida);
            this.$grid.on('rowdoubleclick', function (event) {
                self.otkrit_okno_prosmotra_napravlenie(event);
            });
        }

        get nastroiki_grida() {
            let self = this;
            return {
                width: '100%',
                height: 'calc(100% - 37px)',
                source: this.data_adapter,
                columns: this.colums,
                enabletooltips: true,
                localization: RUS_LOCALIZ,
                filterable: true,
                showtoolbar: true,
                pageable: true,
                columnsresize: true,
                autorowheight: true,
                scrollmode: 'logical',
                rowsheight: 40,
                toolbarheight: 40,
                theme: 'arctic',
                altrows: true,
                sortable: true,
                showstatusbar: true,
                statusbarheight: 25,
                pagesizeoptions: ['5', '10', '30', '50', '100'],
                pagesize: 30,
            }
        }

        get fields() {
            return [
                {name: 'id', type: 'number'},
                {name: 'data_str', type: 'data'},
                {name: 'punkt_napravleniya_title', type: 'string'},
                {name: 'cel_napravleniya_title', type: 'string'},
                {name: 'diagnoz_podtverjden', type: 'boolean'},
                {name: 'predpolagaemyi_diagnoz', type: 'string'}
            ]
        }

        get colums() {
            return [
                {
                    text: 'ID',
                    datafield: 'id',
                    align: 'center',
                    cellsalign: 'center',
                    width: '10%',

                },
                {
                    text: 'Дата',
                    datafield: 'data_str',
                    align: 'center',
                    cellsalign: 'center',
                    width: '20%',

                },
                {
                    text: 'Учреждение',
                    datafield: 'punkt_napravleniya_title',
                    align: 'center',
                    cellsalign: 'center',
                    width: '20%',

                },
                {
                    text: 'Цель',
                    datafield: 'cel_napravleniya_title',
                    align: 'center',
                    cellsalign: 'center',
                    width: '10%',

                },
                 {
                    text: 'Диагноз',
                    datafield: 'predpolagaemyi_diagnoz',
                    align: 'center',
                    cellsalign: 'center',
                    width: '30%',

                },
                {
                    text: 'Диагноз подтв.',
                    datafield: 'diagnoz_podtverjden',
                    align: 'center',
                    cellsalign: 'center',
                    width: '10%',

                },

            ];
        }

        get data_adapter() {
            if (NAPRAVLENIE_ID=0) {
               return new $.jqx.dataAdapter({
                datatype: "json",
                data: 'data',
                url:`/api2/napravlenie/`,
                datafields: this.fields,
                sortcolumn: 'id',
                sortdirection: 'desc'
                });}
            return new $.jqx.dataAdapter({
                datatype: "json",
                data: 'data',
                url: `/api2/napravlenie/${BEREMENYA_ID}`,
                datafields: this.fields,
                sortcolumn: 'id',
                sortdirection: 'desc'
                });

        }
        otkrit_okno_prosmotra_napravlenie(event) {
            let args = event.args;
            let id = (args.row.bounddata.id);
            this.obj_window_napravlenie.open(id)
        }
    }


    let $tabliza_napravlenie = $('.tabliza_napravlenie');


</script>

apps/core/templates/beremennya/beremennaya_tabs/napravlenie/window_napravlenie.html
<style>
    .window_napravlenie .jqx-tabs-headerWrapper {
        display: none;
    }

    .window_napravlenie .jqx-window-header {
        height: 16px;
        padding: 7px;
    }

    .window_napravlenie .FixP label {

        width: auto;

    }


    .window_napravlenie p {
        margin: 1px 0 1px 0;
        background-color: #dee0e2;
        float: left;
        width: 100%;
        display: inline-flex;
    }

    .window_napravlenie label {
        margin: 7px 5px 7px 0;
        width: 50%;
        float: left;
        text-align: right;
        height: auto;
    }

    .window_napravlenie select {
        margin: 4px 3px 4px 3px;
        width: 250px;
        height: 20px;
        outline: none;
        border: 1px solid transparent;
        border-radius: 4px;
    }

    .window_napravlenie input [type="text"] {
        width: 245px !important;
    }

    input[type="date" i] {
        width: 250px !important;
        margin: 4px 3px 4px 3px;
        outline: none;
        border: 1px solid transparent;
        border-radius: 4px
    }

    .window_napravlenie input[type="checkbox"] {
        width: 16px;
        height: 16px;
        margin: 7px 5px 7px 0;
        opacity: 1;
        background: -webkit-gradient(linear, 0 0, 0 100%, from(#f8f8f8), to(#eaeaea));
        color: #333333;
        text-shadow: 0 1px 1px rgb(255 255 255);
        border-radius: 4px;
        font-family: Verdana, Arial, sans-serif;
        border: 1px solid transparent;
        outline: none;
    }

    .window_napravlenie .save_napravlenie {
        position: relative;
        left: 43%;
        width: 200px;
        margin: 3px;
    }

    .window_napravlenie .default {
        align-items: center;
        margin: 1px 0 1px 0;
        background-color: #dee0e2;
        float: left;
        width: 100%;
        display: inline-flex;
    }

    .window_napravlenie h3 {
        font-style: italic;
        text-align: center;
        margin: 0;
    }


</style>
<div class="window_napravlenie">
    <div style="overflow: hidden; padding: 0" class="tab_napravlenie">
        <ul>
            <li></li>
        </ul>
        <div class="tab_beremennya_napravlenie">
            <form id="novoe_napravlenie" class="novoe_napravlenie" action="{% url 'home' %}" method="post">
                {% csrf_token %}


                {{ napravlenie_form.as_p }}

                <div style="position: sticky; bottom: 0;" class="default">
                    <button class="menubtn save_napravlenie" type="submit">Сохранить</button>
                </div>
            </form>
        </div>
    </div>
</div>

<script>


    class WindowNapravlenie {
        constructor($window_napravlenie, $tab, $btn_open_window_napravlenie) {
            let self = this;
            this.$window = $window_napravlenie;
            this.$tab = $tab;
            this.$btn_open_window = $btn_open_window_napravlenie;
            this.$window.jqxWindow({
                position: {x: '15%', y: '10%'},
                maxHeight: 1000,
                maxWidth: 2200,
                minHeight: 387,
                minWidth: 700,
                theme: 'arctic',
                height: 387,
                width: '60%',
                title: 'Новое направление',
                autoOpen: false,
                resizable: false,
                draggable: true,
                initContent: function () {
                    $(self.$tab).jqxTabs({
                        height: 'calc(100% -24px)',
                        width: '100%',
                        theme: 'arctic',
                    });
                }
            });

            this.on_close();
        }

        open2(id) {
            this.$window.find(`#id_nomer_beremennoy option[value="${id}"]`).prop('selected', true);
            this.$window.jqxWindow('open');
        }

        open(id = 0) {
            let self = this;
            if (id) {
                  NAPRAVLENIE_ID = id;
                fetch(`/api2/napravlenie/${BEREMENYA_ID}/${id}`).then(function (response) {
                    if (response.ok) {
                        response.json().then(function (data) {
                            self.$window.find('#id_nomer_beremennoy').val(data['nomer_beremennoy']);
                            self.$window.find('#id_cel_napravleniya').val(data['cel_napravleniya']);
                            self.$window.find('#id_punkt_napravleniya').val(data['punkt_napravleniya']);
                            self.$window.find('#id_predpolagaemyi_diagnoz').val(data['predpolagaemyi_diagnoz']);
                            self.$window.find('#id_diagnoz_podtverjden').val(data['diagnoz_podtverjden']);
                            self.$window.find('#id_data').val(data['data']);
                            self.$window.jqxWindow('open');
                            self.$window.jqxWindow('bringToFront');
                            {#если есть id - значит редачим. Если редачим значить есть url+id#}
                            let url = `/api2/napravlenie/${NAPRAVLENIE_ID}`;
                            $('.novoe_napravlenie').attr('action', `${url}${id}`);
                        }).catch(function () {
                            $('.novoe_napravlenie').action(url)
                            alert('Не могу получить JSON ');
                        })

                    } else {
                        alert('Не могу получить данные');
                    }
                })

            } else {

                let url = `/api2/napravlenie/${NAPRAVLENIE_ID}`;
                $('.novoe_napravlenie').action(url)
            }

        }


        on_close() {
            let self = this;
            this.$window.on('close', function () {
                self.$btn_open_window.jqxToggleButton('toggled', false);
            });
        }

    }

    let $window_napravlenie = $('.window_napravlenie');
    let $tab_napravlenie = $('.tab_napravlenie');
    let obj_window_napravlenie = new WindowNapravlenie($window_napravlenie, $tab_napravlenie, $btn_open_window_napravlenie);
    $(function () {
        new WindowNapravlenie($window_napravlenie, $tab_napravlenie, $btn_open_window_napravlenie)
    })

</script>